# Generated by Django 5.1.6 on 2025-03-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_ausgaben'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.AddField(
            model_name='ausgaben',
            name='month',
            field=models.CharField(default='', max_length=200),
        ),
    ]
