# Generated by Django 5.1.6 on 2025-03-04 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_delete_todoitem_ausgaben_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausgaben',
            name='type',
            field=models.CharField(choices=[('E', 'Einnahmen'), ('A', 'Ausgaben')], default='A', help_text='Einnahme oder Ausgabe.', max_length=1),
        ),
        migrations.AlterField(
            model_name='ausgaben',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Betrag der Ausgabe.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ausgaben',
            name='category',
            field=models.CharField(choices=[('W', 'Wohnen'), ('L', 'Leben'), ('H/F', 'Hobby/Freizeit'), ('M', 'Mobilität'), ('B', 'Bildung'), ('S/I', 'Sparen/Investieren'), ('S', 'Sonstiges')], help_text='Kategorie der Ausgabe.', max_length=10),
        ),
        migrations.AlterField(
            model_name='ausgaben',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Einzigartige ID für jeden Eintrag.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ausgaben',
            name='month',
            field=models.CharField(choices=[('01', 'Januar'), ('02', 'Februar'), ('03', 'März'), ('04', 'April'), ('05', 'Mai'), ('06', 'Juni'), ('07', 'Juli'), ('08', 'August'), ('09', 'September'), ('10', 'Oktober'), ('11', 'November'), ('12', 'Dezember')], default=('03', 'März'), help_text='Monat der Ausgabe.', max_length=10),
        ),
        migrations.AlterField(
            model_name='ausgaben',
            name='title',
            field=models.CharField(help_text='Bezeichnung der Ausgabe.', max_length=30),
        ),
    ]
