# Generated by Django 5.1.6 on 2025-03-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0004_ausgaben_type_alter_ausgaben_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausgaben',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
